remove legacy mode and bind api to emitter
ssbc/muxrpc pull request #83
Opened 2023-11-20 08:41 UTC by staltz

## Context

In [secret-stack I recently added support for more identifiers](https://github.com/ssbc/secret-stack/pull/86) so that we can different kinds of IDs depending on the muxrpc transformer used (secret-handshake? no-auth? secret-handshake-extended? etc)

## Problem

muxrpc still used

```js
createLocalApi(localApi, localManifest, perms).bind(context)
```

where "context" is

```
const context = { _emit, id }
```

which means the `id` is hard-coded. This `id` comes from [secret-stack](https://github.com/ssbc/secret-stack/blob/967adf3324a27606c61fc5629b0db86867b6e4d5/lib/core.js#L279) and then is available for reading as `this.id` where the `this` is referring to the remote peer. [Concrete use case here.](https://github.com/ssbc/ssb-room-client/blob/0815665f58949b7795f2308ca9757cc4f638f50a/src/plugin-tunnel.ts#L51)

The problem is that with diverse IDs, `this.shse.pubkey` is not available, because the `context` object doesn't have that information. We need to bind to the emitter instead:

```js
createLocalApi(localApi, localManifest, perms).bind(emitter)
```

## Solution

I started by binding to the emitter, and that made the `context` useless (unused anywhere) which in turn led me to remove the legacy mode and some of the `index.js`, which in turn led to adapting all the tests (they all assumed the legacy mode), that's why this PR looks big. It's all a domino effect from binding to the emitter.

**This PR is a breaking change and should be published as a new major version.**

## Tests

All tests passed when I ran them locally. Standard linting also passed.

2023-11-20 11:41 UTC, mycognosist requested changes
I've not personally used this part of the JS stack but from reading the code changes and tests it looks good to me 🟢 

Maybe a README update is in order, since the function signature of `createMuxrpc` has changed?

https://github.com/ssbc/muxrpc#api-createmuxrpc-remotemanifest-localmanifest-localapi-id-perms-codec-legacy--rpc

2023-11-20 11:44 UTC, staltz commented
Oh, great point, I gotta update that. Thanks!

2023-11-21 08:34 UTC, staltz commented
Updated the readme now :)

2023-11-21 09:56 UTC, mycognosist approved these changes
Beautiful! Great work 🟢

2023-11-21 10:15 UTC, merged